import base64
import hashlib
import hmac
import logging
import os
from typing import Any, Dict, Optional
import httpx

logger = logging.getLogger(__name__)

RAZORPAY_API_BASE = "https://api.razorpay.com/v1"


class RazorpayService:
    """
    Razorpay Payment Gateway Service with dynamic credentials.
    Supports Order Creation, HMAC SHA-256 Signature Verification, Dynamic QR Codes,
    Payment Links, Webhooks, Instant Refunds, and Live Connection Testing.
    Strictly uses authentic Razorpay REST APIs without hardcoded mock fallbacks.
    """

    def __init__(
        self,
        key_id: Optional[str] = None,
        key_secret: Optional[str] = None,
        webhook_secret: Optional[str] = None,
    ):
        self.key_id = (key_id or os.getenv("RAZORPAY_KEY_ID", "rzp_test_RCEmjSWmFaZJbN")).strip()
        self.key_secret = (key_secret or os.getenv("RAZORPAY_KEY_SECRET", "IGLluMDmPXFRpqDd4MZ7PwBB")).strip()
        self.webhook_secret = (webhook_secret or os.getenv("RAZORPAY_WEBHOOK_SECRET", "")).strip()

    def _get_auth_header(self) -> Dict[str, str]:
        auth_bytes = f"{self.key_id}:{self.key_secret}".encode("ascii")
        b64_auth = base64.b64encode(auth_bytes).decode("ascii")
        return {
            "Authorization": f"Basic {b64_auth}",
            "Content-Type": "application/json",
        }

    async def test_connection(self) -> Dict[str, Any]:
        """Validates Razorpay Key ID and Key Secret by hitting the /payments endpoint."""
        if not self.key_id or not self.key_secret:
            return {"success": False, "message": "Razorpay Key ID and Key Secret cannot be empty."}

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                res = await client.get(
                    f"{RAZORPAY_API_BASE}/payments?count=1",
                    headers=self._get_auth_header(),
                )
                if res.status_code == 200:
                    return {
                        "success": True,
                        "message": "Razorpay credentials successfully authenticated with live API.",
                        "mode": "test" if "test" in self.key_id.lower() else "live",
                    }
                else:
                    err_msg = res.json().get("error", {}).get("description", res.text)
                    return {"success": False, "message": f"Razorpay API Error ({res.status_code}): {err_msg}"}
        except Exception as exc:
            logger.error("Razorpay test_connection error: %s", exc)
            return {"success": False, "message": f"Connection failed: {str(exc)}"}

    async def create_order(
        self,
        amount: float,
        currency: str = "INR",
        receipt: Optional[str] = None,
        notes: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Creates a Razorpay Order.
        Amount is converted to smallest currency sub-units (e.g. Paise for INR).
        """
        amount_subunits = int(round(amount * 100))
        payload: Dict[str, Any] = {
            "amount": amount_subunits,
            "currency": currency.upper(),
            "receipt": receipt or f"rcpt_{int(amount)}_{hashlib.md5(str(receipt).encode()).hexdigest()[:6]}",
            "payment_capture": 1,
        }
        if notes:
            payload["notes"] = {str(k): str(v)[:200] for k, v in notes.items()}

        async with httpx.AsyncClient(timeout=15.0) as client:
            res = await client.post(
                f"{RAZORPAY_API_BASE}/orders",
                json=payload,
                headers=self._get_auth_header(),
            )
            if res.status_code not in (200, 201):
                err_data = res.json() if res.headers.get("content-type", "").startswith("application/json") else {}
                err_msg = err_data.get("error", {}).get("description", res.text)
                raise ValueError(f"Failed to create Razorpay Order ({res.status_code}): {err_msg}")
            
            data = res.json()
            data["key_id"] = self.key_id  # Include public key for frontend checkout init
            return data

    def verify_signature(
        self,
        order_id: str,
        payment_id: str,
        signature: str,
    ) -> bool:
        """
        Validates HMAC-SHA256 signature generated by Razorpay Checkout.
        Message: `order_id|payment_id`
        """
        if not self.key_secret or not order_id or not payment_id or not signature:
            return False

        message = f"{order_id}|{payment_id}".encode("utf-8")
        secret_bytes = self.key_secret.encode("utf-8")
        generated_signature = hmac.new(secret_bytes, message, hashlib.sha256).hexdigest()

        return hmac.compare_digest(generated_signature, signature)

    async def fetch_payment(self, payment_id: str) -> Dict[str, Any]:
        """Fetches payment details (status, method, card details, VPA) from Razorpay."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            res = await client.get(
                f"{RAZORPAY_API_BASE}/payments/{payment_id}",
                headers=self._get_auth_header(),
            )
            if res.status_code == 200:
                return res.json()
            raise ValueError(f"Unable to fetch payment {payment_id}: {res.text}")

    async def create_payment_link(
        self,
        amount: float,
        description: str,
        customer_name: Optional[str] = None,
        customer_phone: Optional[str] = None,
        customer_email: Optional[str] = None,
        notify_sms: bool = True,
        notify_email: bool = True,
        notes: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Creates a Razorpay Payment Link that can be shared via SMS, WhatsApp, or Email."""
        amount_subunits = int(round(amount * 100))
        customer_payload: Dict[str, Any] = {}
        if customer_name:
            customer_payload["name"] = customer_name
        if customer_phone:
            clean_phone = "".join(filter(str.isdigit, customer_phone))
            if len(clean_phone) == 10:
                clean_phone = f"+91{clean_phone}"
            elif not clean_phone.startswith("+"):
                clean_phone = f"+{clean_phone}"
            customer_payload["contact"] = clean_phone
        if customer_email:
            customer_payload["email"] = customer_email

        payload: Dict[str, Any] = {
            "amount": amount_subunits,
            "currency": "INR",
            "accept_partial": False,
            "description": description,
            "notify": {
                "sms": notify_sms if customer_phone else False,
                "email": notify_email if customer_email else False,
            },
            "reminder_enable": True,
            "notes": notes or {},
        }
        if customer_payload:
            payload["customer"] = customer_payload

        async with httpx.AsyncClient(timeout=15.0) as client:
            res = await client.post(
                f"{RAZORPAY_API_BASE}/payment_links",
                json=payload,
                headers=self._get_auth_header(),
            )
            if res.status_code not in (200, 201):
                err_data = res.json() if res.headers.get("content-type", "").startswith("application/json") else {}
                err_msg = err_data.get("error", {}).get("description", res.text)
                raise ValueError(f"Failed to create Payment Link: {err_msg}")
            return res.json()

    async def create_qr_code(
        self,
        amount: float,
        name: str = "POS Counter Checkout",
        description: Optional[str] = None,
        notes: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Creates a Razorpay Dynamic UPI QR Code."""
        amount_subunits = int(round(amount * 100))
        payload: Dict[str, Any] = {
            "type": "upi_qr",
            "name": name[:40],
            "usage": "single_use",
            "fixed_amount": True,
            "payment_amount": amount_subunits,
            "description": (description or f"Bill Payment of Rs {amount:.2f}")[:250],
            "notes": notes or {},
        }
        async with httpx.AsyncClient(timeout=15.0) as client:
            res = await client.post(
                f"{RAZORPAY_API_BASE}/payments/qr_codes",
                json=payload,
                headers=self._get_auth_header(),
            )
            if res.status_code not in (200, 201):
                err_data = res.json() if res.headers.get("content-type", "").startswith("application/json") else {}
                err_msg = err_data.get("error", {}).get("description", res.text)
                raise ValueError(f"Failed to create Razorpay QR Code: {err_msg}")
            return res.json()

    async def fetch_qr_code(self, qr_id: str) -> Dict[str, Any]:
        """Fetches status and payments of a Razorpay QR Code."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            res = await client.get(
                f"{RAZORPAY_API_BASE}/payments/qr_codes/{qr_id}",
                headers=self._get_auth_header(),
            )
            if res.status_code == 200:
                return res.json()
            raise ValueError(f"Unable to fetch QR code {qr_id}: {res.text}")

    async def fetch_order(self, order_id: str) -> Dict[str, Any]:
        """Fetches status and details of a Razorpay Order."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            res = await client.get(
                f"{RAZORPAY_API_BASE}/orders/{order_id}",
                headers=self._get_auth_header(),
            )
            if res.status_code == 200:
                return res.json()
            raise ValueError(f"Unable to fetch order {order_id}: {res.text}")

    async def fetch_order_payments(self, order_id: str) -> Dict[str, Any]:
        """Fetches all payment attempts associated with a Razorpay Order."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            res = await client.get(
                f"{RAZORPAY_API_BASE}/orders/{order_id}/payments",
                headers=self._get_auth_header(),
            )
            if res.status_code == 200:
                return res.json()
            raise ValueError(f"Unable to fetch order payments for {order_id}: {res.text}")

    async def fetch_payment_link(self, link_id: str) -> Dict[str, Any]:
        """Fetches live status of a Razorpay Payment Link."""
        async with httpx.AsyncClient(timeout=10.0) as client:
            res = await client.get(
                f"{RAZORPAY_API_BASE}/payment_links/{link_id}",
                headers=self._get_auth_header(),
            )
            if res.status_code == 200:
                return res.json()
            raise ValueError(f"Unable to fetch payment link {link_id}: {res.text}")

    def verify_webhook(self, payload_body: bytes, signature: str) -> bool:
        """Validates incoming Razorpay webhook signature."""
        if not self.webhook_secret or not signature:
            return False
        secret_bytes = self.webhook_secret.encode("utf-8")
        generated_signature = hmac.new(secret_bytes, payload_body, hashlib.sha256).hexdigest()
        return hmac.compare_digest(generated_signature, signature)

    async def create_refund(
        self,
        payment_id: str,
        amount: Optional[float] = None,
        notes: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Creates a full or partial refund for a captured Razorpay payment."""
        payload: Dict[str, Any] = {"notes": notes or {}}
        if amount is not None and amount > 0:
            payload["amount"] = int(round(amount * 100))

        async with httpx.AsyncClient(timeout=15.0) as client:
            res = await client.post(
                f"{RAZORPAY_API_BASE}/payments/{payment_id}/refund",
                json=payload,
                headers=self._get_auth_header(),
            )
            if res.status_code not in (200, 201):
                err_msg = res.json().get("error", {}).get("description", res.text)
                raise ValueError(f"Failed to process refund: {err_msg}")
            return res.json()
