import {
  LayoutDashboard, Building2, MapPin, CreditCard, ToggleLeft, IndianRupee,
  Monitor, Sparkles, BarChart3, Settings, Users, CalendarCheck, UserCog,
  Dumbbell, Apple, KanbanSquare, ShoppingCart, Package, Cctv, Fingerprint,
  Ruler, FileBarChart, GitBranch, Calendar, ClipboardList, TrendingUp,
  MessageSquare, User, Home, ScanLine, History, HeartPulse, LogIn,
  UserCheck, UserPlus, UserX, UserMinus, AlertCircle, AlertTriangle,
  Clock, Activity, Flame, Footprints, Shield, Server, TrendingDown,
  CheckCircle, Clipboard, Scan, BarChart, Building, Play, Plus, Search,
  Bell, ChevronRight, ChevronDown, Menu, X, LogOut, Camera, Upload,
  Zap, Target, Award, ChevronLeft, MoreHorizontal, Filter, Download,
  ArrowUpRight, ArrowDownRight, RefreshCw, Wifi, WifiOff, Video,
  Smartphone, Watch, Droplet, Moon, Heart, Scale, Bone, Waves,
  Timer, Pause, Play as PlayIcon, SkipForward, Replace, Check, Edit3,
  Trash2, PlusCircle, Eye, Star, Info, Send,
  ScanFace, Hand, Fingerprint as FingerprintIcon, Cpu, Cable, Usb,
  Bluetooth, Save, ClipboardCheck, CircleDot, CircleCheck,
  CircleAlert, Wand2, Sliders, Split, ChevronsLeftRight, Columns,
  Beef, Coffee, Sunrise, Utensils, GitCommit, BookmarkCheck, UploadCloud,
  Share2, Image as ImageIcon, Copy, ExternalLink, HelpCircle, Layers, Palette, Instagram,
  Phone, PhoneCall, Flag, Mail, MessageCircle, FileText, Tag, Radio, Megaphone, Percent, Headphones,
  Trophy, Crown, Hourglass, Brain, Bed, QrCode, LayoutGrid, List, ShoppingBag,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'grid': LayoutGrid,
  'layout-grid': LayoutGrid,
  'list': List,
  'rows': List,
  'phone': Phone,
  'phone-call': PhoneCall,
  'flag': Flag,
  'mail': Mail,
  'message-circle': MessageCircle,
  'file-text': FileText,
  'tag': Tag,
  'radio': Radio,
  'megaphone': Megaphone,
  'percent': Percent,
  'headphones': Headphones,
  'share-2': Share2,
  'share': Share2,
  'image': ImageIcon,
  'copy': Copy,
  'external-link': ExternalLink,
  'help-circle': HelpCircle,
  'layers': Layers,
  'palette': Palette,
  'instagram': Instagram,
  'trophy': Trophy,
  'crown': Crown,
  'hourglass': Hourglass,
  'brain': Brain,
  'bed': Bed,
  'qr-code': QrCode,
  'wand-2': Wand2,
  'sliders': Sliders,
  'split': Split,
  'chevrons-left-right': ChevronsLeftRight,
  'columns': Columns,
  'beef': Beef,
  'coffee': Coffee,
  'sunrise': Sunrise,
  'utensils': Utensils,
  'git-commit': GitCommit,
  'bookmark-check': BookmarkCheck,
  'upload-cloud': UploadCloud,
  'layout-dashboard': LayoutDashboard,
  'building-2': Building2,
  'building': Building,
  'map-pin': MapPin,
  'credit-card': CreditCard,
  'toggle-left': ToggleLeft,
  'indian-rupee': IndianRupee,
  'monitor': Monitor,
  'sparkles': Sparkles,
  'bar-chart-3': BarChart3,
  'bar-chart': BarChart,
  'settings': Settings,
  'users': Users,
  'calendar-check': CalendarCheck,
  'user-cog': UserCog,
  'dumbbell': Dumbbell,
  'apple': Apple,
  'kanban-square': KanbanSquare,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'purchase': ShoppingBag,
  'package': Package,
  'cctv': Cctv,
  'fingerprint': Fingerprint,
  'ruler': Ruler,
  'file-bar-chart': FileBarChart,
  'git-branch': GitBranch,
  'calendar': Calendar,
  'clipboard-list': ClipboardList,
  'clipboard': Clipboard,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'message-square': MessageSquare,
  'user': User,
  'home': Home,
  'scan-line': ScanLine,
  'scan': Scan,
  'history': History,
  'heart-pulse': HeartPulse,
  'heart': Heart,
  'log-in': LogIn,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-x': UserX,
  'user-minus': UserMinus,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'clock': Clock,
  'activity': Activity,
  'flame': Flame,
  'footprints': Footprints,
  'shield': Shield,
  'server': Server,
  'check-circle': CheckCircle,
  'play': Play,
  'plus': Plus,
  'search': Search,
  'bell': Bell,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'menu': Menu,
  'x': X,
  'log-out': LogOut,
  'camera': Camera,
  'upload': Upload,
  'zap': Zap,
  'target': Target,
  'award': Award,
  'more-horizontal': MoreHorizontal,
  'filter': Filter,
  'download': Download,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  'refresh-cw': RefreshCw,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'video': Video,
  'smartphone': Smartphone,
  'watch': Watch,
  'droplet': Droplet,
  'moon': Moon,
  'scale': Scale,
  'bone': Bone,
  'waves': Waves,
  'timer': Timer,
  'pause': Pause,
  'play-icon': PlayIcon,
  'skip-forward': SkipForward,
  'replace': Replace,
  'check': Check,
  'edit': Edit3,
  'trash': Trash2,
  'plus-circle': PlusCircle,
  'eye': Eye,
  'star': Star,
  'info': Info,
  'send': Send,
  'scan-face': ScanFace,
  'hand': Hand,
  'fingerprint-icon': FingerprintIcon,
  'cpu': Cpu,
  'cable': Cable,
  'usb': Usb,
  'bluetooth': Bluetooth,
  'save': Save,
  'clipboard-check': ClipboardCheck,
  'circle-dot': CircleDot,
  'circle-check': CircleCheck,
  'circle-alert': CircleAlert,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 20, className, strokeWidth = 2 }: IconProps) {
  const Cmp = iconMap[name];
  if (!Cmp) return null;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} />;
}
